linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - bodyclose
    - contextcheck
    - errname
    - errorlint
    - exhaustive
    - goconst
    - gocritic
    - gocyclo
    - gosec
    - prealloc
    - unconvert
    - unparam
    - whitespace

linters-settings:
  govet:
    enable:
      - shadow
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15
  gosec:
    excludes:
      - G304 # File path provided as taint input (expected in file operations)

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - unparam
